name = "bifrost-bridge"
main = "src/index.ts"
compatibility_date = "2026-02-18"

[vars]
# Environment variables

[[kv_namespaces]]
binding = "AEGIS_KV"
id = "be16781ec93e4adc8048ba1edee3d10c"
preview_id = "be16781ec93e4adc8048ba1edee3d10c"
