name: Deploy Worker Bees
on:
  push:
    branches:
      - master
      - main
      - hee-haw
    paths:
      - 'workers/worker-bees/**'
      - '.github/workflows/deploy-worker-bees.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Worker Bee
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: workers/worker-bees
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
