name: Deploy Bifrost

on:
  push:
    branches:
      - main
      - hee-haw
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-events:
    name: Deploy Events Store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: workers/bifrost-events
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-runner:
    name: Deploy Runner
    needs: deploy-events # Optional sequencing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: workers/bifrost-runner
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-worker-bees:
    name: Deploy Worker Bees
    needs: deploy-events # Optional sequencing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: workers/worker-bees
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
